use crate::errors::AppError;
use serde::Serialize;
use std::path::{Path, PathBuf};

const MEDIA_DIR_NAME: &str = "media";
const MAX_IMAGE_BYTES: usize = 5 * 1024 * 1024;
const MAX_VIDEO_BYTES: usize = 50 * 1024 * 1024;
const IMAGE_EXTENSIONS: [&str; 6] = ["png", "jpg", "jpeg", "webp", "avif", "gif"];
const VIDEO_EXTENSIONS: [&str; 1] = ["mp4"];

#[derive(Debug, Clone, Serialize)]
pub struct MediaSaved {
    pub name: String,
    pub path: String,
    pub size_bytes: u64,
}

fn media_dir(data_dir: &Path) -> PathBuf {
    data_dir.join(MEDIA_DIR_NAME)
}

fn extension_allowed(kind: &str, ext: &str) -> bool {
    match kind {
        "image" => IMAGE_EXTENSIONS.contains(&ext),
        "video" => VIDEO_EXTENSIONS.contains(&ext),
        _ => false,
    }
}

fn max_bytes_for(kind: &str) -> usize {
    match kind {
        "image" => MAX_IMAGE_BYTES,
        "video" => MAX_VIDEO_BYTES,
        _ => 0,
    }
}

/// Store uploaded theme media under `<data_dir>/media/<uuid>.<ext>` and
/// return the absolute path so the desktop webview can load it through the
/// Tauri asset protocol. Bytes and names are validated before touching disk.
pub fn save_media_file(
    data_dir: &Path,
    kind: &str,
    file_name: &str,
    bytes: &[u8],
) -> Result<MediaSaved, AppError> {
    let ext = file_name
        .rsplit('.')
        .next()
        .unwrap_or_default()
        .to_ascii_lowercase();
    if !extension_allowed(kind, &ext) {
        return Err(AppError::InvalidInput(format!(
            "Unsupported {} type: .{}",
            kind, ext
        )));
    }
    let max = max_bytes_for(kind);
    if bytes.len() > max {
        return Err(AppError::InvalidInput(format!(
            "{} exceeds the {} MB {} size limit",
            file_name,
            max / (1024 * 1024),
            kind
        )));
    }

    let dir = media_dir(data_dir);
    std::fs::create_dir_all(&dir)?;
    let name = format!("{}.{}", uuid::Uuid::new_v4().simple(), ext);
    let path = dir.join(&name);
    std::fs::write(&path, bytes)?;

    Ok(MediaSaved {
        name,
        path: path.to_string_lossy().to_string(),
        size_bytes: bytes.len() as u64,
    })
}

/// Resolve a stored media file for serving. Names are generated by
/// `save_media_file` (`<uuid>.<ext>`), so anything else is rejected before
/// it can reach the filesystem.
pub fn media_path_by_name(data_dir: &Path, name: &str) -> Result<PathBuf, AppError> {
    let invalid = || AppError::InvalidInput(format!("Invalid media name: {}", name));
    let (stem, ext) = name.rsplit_once('.').ok_or_else(invalid)?;
    let ext = ext.to_ascii_lowercase();
    if uuid::Uuid::parse_str(stem).is_err() || !extension_allowed("image", &ext) && !extension_allowed("video", &ext)
    {
        return Err(invalid());
    }

    let path = media_dir(data_dir).join(name);
    if !path.is_file() {
        return Err(AppError::NotFound(format!("Media file not found: {}", name)));
    }
    Ok(path)
}

pub fn media_content_type(name: &str) -> &'static str {
    match name
        .rsplit_once('.')
        .map(|(_, ext)| ext.to_ascii_lowercase())
        .as_deref()
    {
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("avif") => "image/avif",
        Some("gif") => "image/gif",
        Some("mp4") => "video/mp4",
        _ => "application/octet-stream",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_data_dir(test_name: &str) -> PathBuf {
        let dir = std::env::temp_dir()
            .join("knowtequiz-media-tests")
            .join(test_name)
            .join(uuid::Uuid::new_v4().to_string());
        std::fs::create_dir_all(&dir).expect("test temp dir should be created");
        dir
    }

    #[test]
    fn save_media_file_stores_image_inside_media_dir() {
        let data_dir = temp_data_dir("save_media_file_stores_image_inside_media_dir");

        let saved = save_media_file(&data_dir, "image", "wallpaper.PNG", b"image-bytes")
            .expect("image should be saved");

        assert!(Path::new(&saved.path).starts_with(data_dir.join("media")));
        assert!(saved.path.ends_with(".png"));
        assert_eq!(saved.size_bytes, 11);
        assert!(data_dir.join("media").join(&saved.name).is_file());
    }

    #[test]
    fn save_media_file_rejects_unsupported_extensions_and_kinds() {
        let data_dir = temp_data_dir("save_media_file_rejects_unsupported_extensions_and_kinds");

        let bad_ext = save_media_file(&data_dir, "image", "wallpaper.svg", b"x");
        assert!(bad_ext.is_err());

        let bad_kind = save_media_file(&data_dir, "audio", "clip.mp3", b"x");
        assert!(bad_kind.is_err());

        let bad_video_ext = save_media_file(&data_dir, "video", "clip.avi", b"x");
        assert!(bad_video_ext.is_err());
    }

    #[test]
    fn save_media_file_rejects_oversized_files() {
        let data_dir = temp_data_dir("save_media_file_rejects_oversized_files");
        let oversized = vec![0u8; MAX_IMAGE_BYTES + 1];

        let result = save_media_file(&data_dir, "image", "big.png", &oversized);

        let err = result.expect_err("oversized image should be rejected");
        assert!(err.to_string().contains("size limit"));
    }

    #[test]
    fn media_path_by_name_accepts_generated_names_only() {
        let data_dir = temp_data_dir("media_path_by_name_accepts_generated_names_only");
        let saved = save_media_file(&data_dir, "video", "lecture.mp4", b"video")
            .expect("video should be saved");

        let resolved =
            media_path_by_name(&data_dir, &saved.name).expect("generated name should resolve");
        assert!(resolved.is_file());

        for hostile in ["../settings.json", "settings.json", "not-a-uuid.mp4", "abc"] {
            let result = media_path_by_name(&data_dir, hostile);
            assert!(result.is_err(), "{} should be rejected", hostile);
        }
    }

    #[test]
    fn media_content_type_maps_known_extensions() {
        assert_eq!(media_content_type("a.png"), "image/png");
        assert_eq!(media_content_type("a.mp4"), "video/mp4");
        assert_eq!(media_content_type("a.avif"), "image/avif");
        assert_eq!(media_content_type("a.txt"), "application/octet-stream");
    }
}
